name: Build Game
run-name: build game

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo add-apt-repository ppa:xmake-io/xmake && sudo apt update && sudo apt-get install -y xmake g++ cmake libx11-dev
      - name: Build project with xmake
        run: xmake
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: build/linux/x86_64/release/game
